# Generated by Django 5.0.1 on 2024-11-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuarioid', models.AutoField(db_column='UsuarioID', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='Nombres', max_length=100)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=100)),
                ('genero', models.CharField(db_column='Genero', max_length=10)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('usuario', models.CharField(db_column='Usuario', max_length=50, unique=True)),
                ('contraseña', models.CharField(db_column='Contraseña', max_length=255)),
                ('rolid', models.IntegerField(db_column='RolID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UsuarioCustom',
        ),
    ]
